export const CHANGE_MYPERSON: string = 'CHANGE_MYPERSON';
export const CHANGE_MYPERSON_PROFILE: string = 'CHANGE_MYPERSON_PROFILE';
export const CHANGE_MYPERSON_FAMILY: string = 'CHANGE_MYPERSON_FAMILY';
export const CHANGE_MYPERSON_LEGAL: string = 'CHANGE_MYPERSON_LEGAL';
export const CHANGE_MYPERSON_RESULT: string = 'CHANGE_MYPERSON_RESULT';
export const CLEAR_MYPERSON: string = 'CLEAR_MYPERSON';

export const CHANGE_MYPARTNER: string = 'CHANGE_MYPARTNER';
export const CHANGE_MYPARTNER_ACTIVE: string = 'CHANGE_MYPARTNER_ACTIVE';
export const CHANGE_MYPARTNER_PROFILE: string = 'CHANGE_MYPARTNER_PROFILE';
export const CHANGE_MYPARTNER_FAMILY: string = 'CHANGE_MYPARTNER_FAMILY';
export const CHANGE_MYPARTNER_LEGAL: string = 'CHANGE_MYPARTNER_LEGAL';
export const CHANGE_MYPARTNER_RESULT: string = 'CHANGE_MYPARTNER_RESULT';
export const CLEAR_MYPARTNER: string = 'CLEAR_MYPARTNER';

export const CHANGE_MYCONNECTION: string = 'CHANGE_MYCONNECTION';
export const CHANGE_MYCONNECTION_PROFILE: string = 'CHANGE_MYCONNECTION_PROFILE';
export const CHANGE_MYCONNECTION_LEGAL: string = 'CHANGE_MYCONNECTION_LEGAL';
export const CHANGE_MYCONNECTION_RESULT: string = 'CHANGE_MYCONNECTION_RESULT';
export const CLEAR_MYCONNECTION: string = 'CLEAR_MYCONNECTION';

export const CHANGE_LOGIN: string = 'CHANGE_LOGIN';
export const CHANGE_APPLICATION: string = 'CHANGE_APPLICATION';

export const PUSH_CONTACT_ATTEMPT: string = 'PUSH_CONTACT_ATTEMPT';
export const CHANGE_LOADED_STATE: string = 'CHANGE_LOADED_STATE';

export const CHANGE_ACCOUNT: string = 'CHANGE_ACCOUNT';
export const CHANGE_SPECIALIST: string = 'CHANGE_SPECIALIST';
export const CLEAR_ACCOUNT: string = 'CLEAR_ACCOUNT';
export const CLEAR_SPECIALIST: string = 'CLEAR_SPECIALIST';
export const UPDATE_SYNC_TIMESTAMP: string = 'UPDATE_SYNC_TIMESTAMP';
export const UPDATE_SYNC_TIMESTAMP_MANUAL: string = 'UPDATE_SYNC_TIMESTAMP_MANUAL';
